<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>yuriks.net</title>
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Orbitron&v1" type="text/css">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans&v1" type="text/css">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Metrophobic&v1" type="text/css">
		<link rel="stylesheet" href="/css/reset.css" type="text/css">
		<link rel="stylesheet" href="/css/main.css" type="text/css">
	</head>
	<body>
		<nav><div id="header">
			<h1><a href="/">yuriks.net</a></h1>
			<div id="menu">
				<ul>
					<li><a href="/">About</a></li>
					<li><a href="/projects/">Projects</a></li>
					<li><a href="/stats.html">Stats</a></li>
				</ul>
			</div>
		</div></nav>
